/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ProfileDangerRouteImport } from './routes/profile/danger'
import { Route as ProfileAuthorizationsRouteImport } from './routes/profile/authorizations'
import { Route as ProfileAuthenticationRouteImport } from './routes/profile/authentication'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProfileDangerRoute = ProfileDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileAuthorizationsRoute = ProfileAuthorizationsRouteImport.update({
  id: '/authorizations',
  path: '/authorizations',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileAuthenticationRoute = ProfileAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/verify-2fa': typeof Verify2faRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/profile/authentication': typeof ProfileAuthenticationRoute
  '/profile/authorizations': typeof ProfileAuthorizationsRoute
  '/profile/danger': typeof ProfileDangerRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/verify-2fa': typeof Verify2faRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/profile/authentication': typeof ProfileAuthenticationRoute
  '/profile/authorizations': typeof ProfileAuthorizationsRoute
  '/profile/danger': typeof ProfileDangerRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/profile': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/verify-2fa': typeof Verify2faRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/profile/authentication': typeof ProfileAuthenticationRoute
  '/profile/authorizations': typeof ProfileAuthorizationsRoute
  '/profile/danger': typeof ProfileDangerRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/projects'
    | '/about'
    | '/admin'
    | '/career'
    | '/contact'
    | '/cookie'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/verify-2fa'
    | '/oauth/consent'
    | '/profile/authentication'
    | '/profile/authorizations'
    | '/profile/danger'
    | '/projects/$slug'
    | '/profile/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/about'
    | '/admin'
    | '/career'
    | '/contact'
    | '/cookie'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/verify-2fa'
    | '/oauth/consent'
    | '/profile/authentication'
    | '/profile/authorizations'
    | '/profile/danger'
    | '/projects/$slug'
    | '/profile'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/projects'
    | '/about'
    | '/admin'
    | '/career'
    | '/contact'
    | '/cookie'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/verify-2fa'
    | '/oauth/consent'
    | '/profile/authentication'
    | '/profile/authorizations'
    | '/profile/danger'
    | '/projects/$slug'
    | '/profile/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  CookieRoute: typeof CookieRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  Verify2faRoute: typeof Verify2faRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/profile/danger': {
      id: '/profile/danger'
      path: '/danger'
      fullPath: '/profile/danger'
      preLoaderRoute: typeof ProfileDangerRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/authorizations': {
      id: '/profile/authorizations'
      path: '/authorizations'
      fullPath: '/profile/authorizations'
      preLoaderRoute: typeof ProfileAuthorizationsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/authentication': {
      id: '/profile/authentication'
      path: '/authentication'
      fullPath: '/profile/authentication'
      preLoaderRoute: typeof ProfileAuthenticationRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteRouteChildren {
  ProfileAuthenticationRoute: typeof ProfileAuthenticationRoute
  ProfileAuthorizationsRoute: typeof ProfileAuthorizationsRoute
  ProfileDangerRoute: typeof ProfileDangerRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileAuthenticationRoute: ProfileAuthenticationRoute,
  ProfileAuthorizationsRoute: ProfileAuthorizationsRoute,
  ProfileDangerRoute: ProfileDangerRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface ProjectsRouteRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  CookieRoute: CookieRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  Verify2faRoute: Verify2faRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
