/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ArchiveSlugRouteRouteImport } from './routes/$archiveSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ArchiveSlugIndexRouteImport } from './routes/$archiveSlug/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as MediaSplatRouteImport } from './routes/media/$'
import { Route as ArchiveSlugSplatRouteImport } from './routes/$archiveSlug/$'
import { Route as DashboardProfileRouteRouteImport } from './routes/dashboard/profile/route'
import { Route as DashboardCmsRouteRouteImport } from './routes/dashboard/cms/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardCmsIndexRouteImport } from './routes/dashboard/cms/index'
import { Route as DashboardProfileDangerRouteImport } from './routes/dashboard/profile/danger'
import { Route as DashboardProfileAuthorizationsRouteImport } from './routes/dashboard/profile/authorizations'
import { Route as DashboardProfileAuthenticationRouteImport } from './routes/dashboard/profile/authentication'
import { Route as DashboardCmsTagsRouteImport } from './routes/dashboard/cms/tags'
import { Route as DashboardCmsOrganizationsRouteImport } from './routes/dashboard/cms/organizations'
import { Route as DashboardCmsMediaRouteImport } from './routes/dashboard/cms/media'
import { Route as DashboardCmsCategoriesRouteImport } from './routes/dashboard/cms/categories'
import { Route as DashboardCmsArticlesRouteImport } from './routes/dashboard/cms/articles'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardCmsArticlesNewRouteImport } from './routes/dashboard/cms/articles_.new'
import { Route as DashboardCmsArticlesArticleIdRouteImport } from './routes/dashboard/cms/articles_.$articleId'
import { Route as DashboardAdminUsersNewRouteImport } from './routes/dashboard/admin/users_.new'
import { Route as ApiContentV1TagsRouteImport } from './routes/api/content/v1/tags'
import { Route as ApiContentV1CategoriesRouteImport } from './routes/api/content/v1/categories'
import { Route as ApiCmsMediaUploadRouteImport } from './routes/api/cms/media/upload'
import { Route as ApiContentV1ArticlesIndexRouteImport } from './routes/api/content/v1/articles/index'
import { Route as DashboardCmsArticlesArticleIdPreviewRouteImport } from './routes/dashboard/cms/articles_.$articleId_.preview'
import { Route as ApiContentV1ArticlesSlugRouteImport } from './routes/api/content/v1/articles/$slug'

const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSlugRouteRoute = ArchiveSlugRouteRouteImport.update({
  id: '/$archiveSlug',
  path: '/$archiveSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ArchiveSlugIndexRoute = ArchiveSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveSlugRouteRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSlugSplatRoute = ArchiveSlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ArchiveSlugRouteRoute,
} as any)
const DashboardProfileRouteRoute = DashboardProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCmsRouteRoute = DashboardCmsRouteRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProfileRouteRoute,
} as any)
const DashboardCmsIndexRoute = DashboardCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCmsRouteRoute,
} as any)
const DashboardProfileDangerRoute = DashboardProfileDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => DashboardProfileRouteRoute,
} as any)
const DashboardProfileAuthorizationsRoute =
  DashboardProfileAuthorizationsRouteImport.update({
    id: '/authorizations',
    path: '/authorizations',
    getParentRoute: () => DashboardProfileRouteRoute,
  } as any)
const DashboardProfileAuthenticationRoute =
  DashboardProfileAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => DashboardProfileRouteRoute,
  } as any)
const DashboardCmsTagsRoute = DashboardCmsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => DashboardCmsRouteRoute,
} as any)
const DashboardCmsOrganizationsRoute =
  DashboardCmsOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => DashboardCmsRouteRoute,
  } as any)
const DashboardCmsMediaRoute = DashboardCmsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardCmsRouteRoute,
} as any)
const DashboardCmsCategoriesRoute = DashboardCmsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardCmsRouteRoute,
} as any)
const DashboardCmsArticlesRoute = DashboardCmsArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => DashboardCmsRouteRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCmsArticlesNewRoute = DashboardCmsArticlesNewRouteImport.update({
  id: '/articles_/new',
  path: '/articles/new',
  getParentRoute: () => DashboardCmsRouteRoute,
} as any)
const DashboardCmsArticlesArticleIdRoute =
  DashboardCmsArticlesArticleIdRouteImport.update({
    id: '/articles_/$articleId',
    path: '/articles/$articleId',
    getParentRoute: () => DashboardCmsRouteRoute,
  } as any)
const DashboardAdminUsersNewRoute = DashboardAdminUsersNewRouteImport.update({
  id: '/users_/new',
  path: '/users/new',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const ApiContentV1TagsRoute = ApiContentV1TagsRouteImport.update({
  id: '/api/content/v1/tags',
  path: '/api/content/v1/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentV1CategoriesRoute = ApiContentV1CategoriesRouteImport.update({
  id: '/api/content/v1/categories',
  path: '/api/content/v1/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsMediaUploadRoute = ApiCmsMediaUploadRouteImport.update({
  id: '/api/cms/media/upload',
  path: '/api/cms/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentV1ArticlesIndexRoute =
  ApiContentV1ArticlesIndexRouteImport.update({
    id: '/api/content/v1/articles/',
    path: '/api/content/v1/articles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCmsArticlesArticleIdPreviewRoute =
  DashboardCmsArticlesArticleIdPreviewRouteImport.update({
    id: '/articles_/$articleId_/preview',
    path: '/articles/$articleId/preview',
    getParentRoute: () => DashboardCmsRouteRoute,
  } as any)
const ApiContentV1ArticlesSlugRoute =
  ApiContentV1ArticlesSlugRouteImport.update({
    id: '/api/content/v1/articles/$slug',
    path: '/api/content/v1/articles/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$archiveSlug': typeof ArchiveSlugRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-2fa': typeof Verify2faRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/cms': typeof DashboardCmsRouteRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRouteRouteWithChildren
  '/$archiveSlug/$': typeof ArchiveSlugSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/$archiveSlug/': typeof ArchiveSlugIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/cms/articles': typeof DashboardCmsArticlesRoute
  '/dashboard/cms/categories': typeof DashboardCmsCategoriesRoute
  '/dashboard/cms/media': typeof DashboardCmsMediaRoute
  '/dashboard/cms/organizations': typeof DashboardCmsOrganizationsRoute
  '/dashboard/cms/tags': typeof DashboardCmsTagsRoute
  '/dashboard/profile/authentication': typeof DashboardProfileAuthenticationRoute
  '/dashboard/profile/authorizations': typeof DashboardProfileAuthorizationsRoute
  '/dashboard/profile/danger': typeof DashboardProfileDangerRoute
  '/dashboard/cms/': typeof DashboardCmsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/api/cms/media/upload': typeof ApiCmsMediaUploadRoute
  '/api/content/v1/categories': typeof ApiContentV1CategoriesRoute
  '/api/content/v1/tags': typeof ApiContentV1TagsRoute
  '/dashboard/admin/users/new': typeof DashboardAdminUsersNewRoute
  '/dashboard/cms/articles/$articleId': typeof DashboardCmsArticlesArticleIdRoute
  '/dashboard/cms/articles/new': typeof DashboardCmsArticlesNewRoute
  '/api/content/v1/articles/$slug': typeof ApiContentV1ArticlesSlugRoute
  '/dashboard/cms/articles/$articleId/preview': typeof DashboardCmsArticlesArticleIdPreviewRoute
  '/api/content/v1/articles/': typeof ApiContentV1ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-2fa': typeof Verify2faRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/$archiveSlug/$': typeof ArchiveSlugSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/$archiveSlug': typeof ArchiveSlugIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/cms/articles': typeof DashboardCmsArticlesRoute
  '/dashboard/cms/categories': typeof DashboardCmsCategoriesRoute
  '/dashboard/cms/media': typeof DashboardCmsMediaRoute
  '/dashboard/cms/organizations': typeof DashboardCmsOrganizationsRoute
  '/dashboard/cms/tags': typeof DashboardCmsTagsRoute
  '/dashboard/profile/authentication': typeof DashboardProfileAuthenticationRoute
  '/dashboard/profile/authorizations': typeof DashboardProfileAuthorizationsRoute
  '/dashboard/profile/danger': typeof DashboardProfileDangerRoute
  '/dashboard/cms': typeof DashboardCmsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/api/cms/media/upload': typeof ApiCmsMediaUploadRoute
  '/api/content/v1/categories': typeof ApiContentV1CategoriesRoute
  '/api/content/v1/tags': typeof ApiContentV1TagsRoute
  '/dashboard/admin/users/new': typeof DashboardAdminUsersNewRoute
  '/dashboard/cms/articles/$articleId': typeof DashboardCmsArticlesArticleIdRoute
  '/dashboard/cms/articles/new': typeof DashboardCmsArticlesNewRoute
  '/api/content/v1/articles/$slug': typeof ApiContentV1ArticlesSlugRoute
  '/dashboard/cms/articles/$articleId/preview': typeof DashboardCmsArticlesArticleIdPreviewRoute
  '/api/content/v1/articles': typeof ApiContentV1ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$archiveSlug': typeof ArchiveSlugRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-2fa': typeof Verify2faRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/cms': typeof DashboardCmsRouteRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRouteRouteWithChildren
  '/$archiveSlug/$': typeof ArchiveSlugSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/$archiveSlug/': typeof ArchiveSlugIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/cms/articles': typeof DashboardCmsArticlesRoute
  '/dashboard/cms/categories': typeof DashboardCmsCategoriesRoute
  '/dashboard/cms/media': typeof DashboardCmsMediaRoute
  '/dashboard/cms/organizations': typeof DashboardCmsOrganizationsRoute
  '/dashboard/cms/tags': typeof DashboardCmsTagsRoute
  '/dashboard/profile/authentication': typeof DashboardProfileAuthenticationRoute
  '/dashboard/profile/authorizations': typeof DashboardProfileAuthorizationsRoute
  '/dashboard/profile/danger': typeof DashboardProfileDangerRoute
  '/dashboard/cms/': typeof DashboardCmsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/api/cms/media/upload': typeof ApiCmsMediaUploadRoute
  '/api/content/v1/categories': typeof ApiContentV1CategoriesRoute
  '/api/content/v1/tags': typeof ApiContentV1TagsRoute
  '/dashboard/admin/users_/new': typeof DashboardAdminUsersNewRoute
  '/dashboard/cms/articles_/$articleId': typeof DashboardCmsArticlesArticleIdRoute
  '/dashboard/cms/articles_/new': typeof DashboardCmsArticlesNewRoute
  '/api/content/v1/articles/$slug': typeof ApiContentV1ArticlesSlugRoute
  '/dashboard/cms/articles_/$articleId_/preview': typeof DashboardCmsArticlesArticleIdPreviewRoute
  '/api/content/v1/articles/': typeof ApiContentV1ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$archiveSlug'
    | '/dashboard'
    | '/about'
    | '/career'
    | '/contact'
    | '/cookie'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/verify-2fa'
    | '/dashboard/admin'
    | '/dashboard/cms'
    | '/dashboard/profile'
    | '/$archiveSlug/$'
    | '/media/$'
    | '/oauth/consent'
    | '/$archiveSlug/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/users'
    | '/dashboard/cms/articles'
    | '/dashboard/cms/categories'
    | '/dashboard/cms/media'
    | '/dashboard/cms/organizations'
    | '/dashboard/cms/tags'
    | '/dashboard/profile/authentication'
    | '/dashboard/profile/authorizations'
    | '/dashboard/profile/danger'
    | '/dashboard/cms/'
    | '/dashboard/profile/'
    | '/api/cms/media/upload'
    | '/api/content/v1/categories'
    | '/api/content/v1/tags'
    | '/dashboard/admin/users/new'
    | '/dashboard/cms/articles/$articleId'
    | '/dashboard/cms/articles/new'
    | '/api/content/v1/articles/$slug'
    | '/dashboard/cms/articles/$articleId/preview'
    | '/api/content/v1/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/cookie'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/verify-2fa'
    | '/dashboard/admin'
    | '/$archiveSlug/$'
    | '/media/$'
    | '/oauth/consent'
    | '/$archiveSlug'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/admin/users'
    | '/dashboard/cms/articles'
    | '/dashboard/cms/categories'
    | '/dashboard/cms/media'
    | '/dashboard/cms/organizations'
    | '/dashboard/cms/tags'
    | '/dashboard/profile/authentication'
    | '/dashboard/profile/authorizations'
    | '/dashboard/profile/danger'
    | '/dashboard/cms'
    | '/dashboard/profile'
    | '/api/cms/media/upload'
    | '/api/content/v1/categories'
    | '/api/content/v1/tags'
    | '/dashboard/admin/users/new'
    | '/dashboard/cms/articles/$articleId'
    | '/dashboard/cms/articles/new'
    | '/api/content/v1/articles/$slug'
    | '/dashboard/cms/articles/$articleId/preview'
    | '/api/content/v1/articles'
  id:
    | '__root__'
    | '/'
    | '/$archiveSlug'
    | '/dashboard'
    | '/about'
    | '/career'
    | '/contact'
    | '/cookie'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/verify-2fa'
    | '/dashboard/admin'
    | '/dashboard/cms'
    | '/dashboard/profile'
    | '/$archiveSlug/$'
    | '/media/$'
    | '/oauth/consent'
    | '/$archiveSlug/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/users'
    | '/dashboard/cms/articles'
    | '/dashboard/cms/categories'
    | '/dashboard/cms/media'
    | '/dashboard/cms/organizations'
    | '/dashboard/cms/tags'
    | '/dashboard/profile/authentication'
    | '/dashboard/profile/authorizations'
    | '/dashboard/profile/danger'
    | '/dashboard/cms/'
    | '/dashboard/profile/'
    | '/api/cms/media/upload'
    | '/api/content/v1/categories'
    | '/api/content/v1/tags'
    | '/dashboard/admin/users_/new'
    | '/dashboard/cms/articles_/$articleId'
    | '/dashboard/cms/articles_/new'
    | '/api/content/v1/articles/$slug'
    | '/dashboard/cms/articles_/$articleId_/preview'
    | '/api/content/v1/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveSlugRouteRoute: typeof ArchiveSlugRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  CookieRoute: typeof CookieRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Verify2faRoute: typeof Verify2faRoute
  MediaSplatRoute: typeof MediaSplatRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCmsMediaUploadRoute: typeof ApiCmsMediaUploadRoute
  ApiContentV1CategoriesRoute: typeof ApiContentV1CategoriesRoute
  ApiContentV1TagsRoute: typeof ApiContentV1TagsRoute
  ApiContentV1ArticlesSlugRoute: typeof ApiContentV1ArticlesSlugRoute
  ApiContentV1ArticlesIndexRoute: typeof ApiContentV1ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$archiveSlug': {
      id: '/$archiveSlug'
      path: '/$archiveSlug'
      fullPath: '/$archiveSlug'
      preLoaderRoute: typeof ArchiveSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/$archiveSlug/': {
      id: '/$archiveSlug/'
      path: '/'
      fullPath: '/$archiveSlug/'
      preLoaderRoute: typeof ArchiveSlugIndexRouteImport
      parentRoute: typeof ArchiveSlugRouteRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$archiveSlug/$': {
      id: '/$archiveSlug/$'
      path: '/$'
      fullPath: '/$archiveSlug/$'
      preLoaderRoute: typeof ArchiveSlugSplatRouteImport
      parentRoute: typeof ArchiveSlugRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/cms': {
      id: '/dashboard/cms'
      path: '/cms'
      fullPath: '/dashboard/cms'
      preLoaderRoute: typeof DashboardCmsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardProfileRouteRoute
    }
    '/dashboard/cms/': {
      id: '/dashboard/cms/'
      path: '/'
      fullPath: '/dashboard/cms/'
      preLoaderRoute: typeof DashboardCmsIndexRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/dashboard/profile/danger': {
      id: '/dashboard/profile/danger'
      path: '/danger'
      fullPath: '/dashboard/profile/danger'
      preLoaderRoute: typeof DashboardProfileDangerRouteImport
      parentRoute: typeof DashboardProfileRouteRoute
    }
    '/dashboard/profile/authorizations': {
      id: '/dashboard/profile/authorizations'
      path: '/authorizations'
      fullPath: '/dashboard/profile/authorizations'
      preLoaderRoute: typeof DashboardProfileAuthorizationsRouteImport
      parentRoute: typeof DashboardProfileRouteRoute
    }
    '/dashboard/profile/authentication': {
      id: '/dashboard/profile/authentication'
      path: '/authentication'
      fullPath: '/dashboard/profile/authentication'
      preLoaderRoute: typeof DashboardProfileAuthenticationRouteImport
      parentRoute: typeof DashboardProfileRouteRoute
    }
    '/dashboard/cms/tags': {
      id: '/dashboard/cms/tags'
      path: '/tags'
      fullPath: '/dashboard/cms/tags'
      preLoaderRoute: typeof DashboardCmsTagsRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/dashboard/cms/organizations': {
      id: '/dashboard/cms/organizations'
      path: '/organizations'
      fullPath: '/dashboard/cms/organizations'
      preLoaderRoute: typeof DashboardCmsOrganizationsRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/dashboard/cms/media': {
      id: '/dashboard/cms/media'
      path: '/media'
      fullPath: '/dashboard/cms/media'
      preLoaderRoute: typeof DashboardCmsMediaRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/dashboard/cms/categories': {
      id: '/dashboard/cms/categories'
      path: '/categories'
      fullPath: '/dashboard/cms/categories'
      preLoaderRoute: typeof DashboardCmsCategoriesRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/dashboard/cms/articles': {
      id: '/dashboard/cms/articles'
      path: '/articles'
      fullPath: '/dashboard/cms/articles'
      preLoaderRoute: typeof DashboardCmsArticlesRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cms/articles_/new': {
      id: '/dashboard/cms/articles_/new'
      path: '/articles/new'
      fullPath: '/dashboard/cms/articles/new'
      preLoaderRoute: typeof DashboardCmsArticlesNewRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/dashboard/cms/articles_/$articleId': {
      id: '/dashboard/cms/articles_/$articleId'
      path: '/articles/$articleId'
      fullPath: '/dashboard/cms/articles/$articleId'
      preLoaderRoute: typeof DashboardCmsArticlesArticleIdRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/dashboard/admin/users_/new': {
      id: '/dashboard/admin/users_/new'
      path: '/users/new'
      fullPath: '/dashboard/admin/users/new'
      preLoaderRoute: typeof DashboardAdminUsersNewRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/content/v1/tags': {
      id: '/api/content/v1/tags'
      path: '/api/content/v1/tags'
      fullPath: '/api/content/v1/tags'
      preLoaderRoute: typeof ApiContentV1TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/v1/categories': {
      id: '/api/content/v1/categories'
      path: '/api/content/v1/categories'
      fullPath: '/api/content/v1/categories'
      preLoaderRoute: typeof ApiContentV1CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/media/upload': {
      id: '/api/cms/media/upload'
      path: '/api/cms/media/upload'
      fullPath: '/api/cms/media/upload'
      preLoaderRoute: typeof ApiCmsMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/v1/articles/': {
      id: '/api/content/v1/articles/'
      path: '/api/content/v1/articles'
      fullPath: '/api/content/v1/articles/'
      preLoaderRoute: typeof ApiContentV1ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cms/articles_/$articleId_/preview': {
      id: '/dashboard/cms/articles_/$articleId_/preview'
      path: '/articles/$articleId/preview'
      fullPath: '/dashboard/cms/articles/$articleId/preview'
      preLoaderRoute: typeof DashboardCmsArticlesArticleIdPreviewRouteImport
      parentRoute: typeof DashboardCmsRouteRoute
    }
    '/api/content/v1/articles/$slug': {
      id: '/api/content/v1/articles/$slug'
      path: '/api/content/v1/articles/$slug'
      fullPath: '/api/content/v1/articles/$slug'
      preLoaderRoute: typeof ApiContentV1ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArchiveSlugRouteRouteChildren {
  ArchiveSlugSplatRoute: typeof ArchiveSlugSplatRoute
  ArchiveSlugIndexRoute: typeof ArchiveSlugIndexRoute
}

const ArchiveSlugRouteRouteChildren: ArchiveSlugRouteRouteChildren = {
  ArchiveSlugSplatRoute: ArchiveSlugSplatRoute,
  ArchiveSlugIndexRoute: ArchiveSlugIndexRoute,
}

const ArchiveSlugRouteRouteWithChildren =
  ArchiveSlugRouteRoute._addFileChildren(ArchiveSlugRouteRouteChildren)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminUsersNewRoute: typeof DashboardAdminUsersNewRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminUsersNewRoute: DashboardAdminUsersNewRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardCmsRouteRouteChildren {
  DashboardCmsArticlesRoute: typeof DashboardCmsArticlesRoute
  DashboardCmsCategoriesRoute: typeof DashboardCmsCategoriesRoute
  DashboardCmsMediaRoute: typeof DashboardCmsMediaRoute
  DashboardCmsOrganizationsRoute: typeof DashboardCmsOrganizationsRoute
  DashboardCmsTagsRoute: typeof DashboardCmsTagsRoute
  DashboardCmsIndexRoute: typeof DashboardCmsIndexRoute
  DashboardCmsArticlesArticleIdRoute: typeof DashboardCmsArticlesArticleIdRoute
  DashboardCmsArticlesNewRoute: typeof DashboardCmsArticlesNewRoute
  DashboardCmsArticlesArticleIdPreviewRoute: typeof DashboardCmsArticlesArticleIdPreviewRoute
}

const DashboardCmsRouteRouteChildren: DashboardCmsRouteRouteChildren = {
  DashboardCmsArticlesRoute: DashboardCmsArticlesRoute,
  DashboardCmsCategoriesRoute: DashboardCmsCategoriesRoute,
  DashboardCmsMediaRoute: DashboardCmsMediaRoute,
  DashboardCmsOrganizationsRoute: DashboardCmsOrganizationsRoute,
  DashboardCmsTagsRoute: DashboardCmsTagsRoute,
  DashboardCmsIndexRoute: DashboardCmsIndexRoute,
  DashboardCmsArticlesArticleIdRoute: DashboardCmsArticlesArticleIdRoute,
  DashboardCmsArticlesNewRoute: DashboardCmsArticlesNewRoute,
  DashboardCmsArticlesArticleIdPreviewRoute:
    DashboardCmsArticlesArticleIdPreviewRoute,
}

const DashboardCmsRouteRouteWithChildren =
  DashboardCmsRouteRoute._addFileChildren(DashboardCmsRouteRouteChildren)

interface DashboardProfileRouteRouteChildren {
  DashboardProfileAuthenticationRoute: typeof DashboardProfileAuthenticationRoute
  DashboardProfileAuthorizationsRoute: typeof DashboardProfileAuthorizationsRoute
  DashboardProfileDangerRoute: typeof DashboardProfileDangerRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
}

const DashboardProfileRouteRouteChildren: DashboardProfileRouteRouteChildren = {
  DashboardProfileAuthenticationRoute: DashboardProfileAuthenticationRoute,
  DashboardProfileAuthorizationsRoute: DashboardProfileAuthorizationsRoute,
  DashboardProfileDangerRoute: DashboardProfileDangerRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
}

const DashboardProfileRouteRouteWithChildren =
  DashboardProfileRouteRoute._addFileChildren(
    DashboardProfileRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardCmsRouteRoute: typeof DashboardCmsRouteRouteWithChildren
  DashboardProfileRouteRoute: typeof DashboardProfileRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardCmsRouteRoute: DashboardCmsRouteRouteWithChildren,
  DashboardProfileRouteRoute: DashboardProfileRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveSlugRouteRoute: ArchiveSlugRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  CookieRoute: CookieRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Verify2faRoute: Verify2faRoute,
  MediaSplatRoute: MediaSplatRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCmsMediaUploadRoute: ApiCmsMediaUploadRoute,
  ApiContentV1CategoriesRoute: ApiContentV1CategoriesRoute,
  ApiContentV1TagsRoute: ApiContentV1TagsRoute,
  ApiContentV1ArticlesSlugRoute: ApiContentV1ArticlesSlugRoute,
  ApiContentV1ArticlesIndexRoute: ApiContentV1ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
